services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
